name: Publish to Crates.io
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-tool-code@v1
      - run: cargo build --release
      - run: cargo test --profile release
      - run: cargo publish --token ${{secrets.CRATES_TOKEN}}
